# Generated by Django 5.2.7 on 2025-10-27 20:40
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profil_resmi_profilguncellemetalebi'),
    ]

    operations = [
        # Önce profil_resmi alanını ekle
        migrations.AddField(
            model_name='customuser',
            name='profil_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='profil_resimleri/', verbose_name='Profil Resmi'),
        ),
        # Sonra yeni model oluştur
        migrations.CreateModel(
            name='ProfilGuncellemeTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeni_telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('yeni_adres', models.TextField(blank=True, null=True)),
                ('yeni_profil_resmi', models.ImageField(blank=True, null=True, upload_to='profil_resimleri/')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('karar_tarihi', models.DateTimeField(blank=True, null=True)),
                ('calisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_talepleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Güncelleme Talebi',
                'verbose_name_plural': 'Profil Güncelleme Talepleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]