# Generated by Django 5.2.7 on 2025-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_profil_guncelleme_talebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilguncellemetalebi',
            name='eski_adres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilguncellemetalebi',
            name='eski_profil_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='profil_resimleri/'),
        ),
        migrations.AddField(
            model_name='profilguncellemetalebi',
            name='eski_telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
