# Generated by Django 5.2.7 on 2025-10-27 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vardiya',
            name='durum',
            field=models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal_istegi', 'İptal İsteği'), ('iptal', 'İptal Edildi'), ('taslak', 'Taslak')], default='taslak', max_length=20),
        ),
        migrations.CreateModel(
            name='VardiyaIptalIstegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('hedef_onayi_bekliyor', 'Hedef Onayı Bekliyor'), ('admin_onayi_bekliyor', 'Admin Onayı Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='admin_onayi_bekliyor', max_length=30)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('istek_yapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderdigi_iptal_istekleri', to=settings.AUTH_USER_MODEL)),
                ('vardiya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iptal_istegi', to='schedules.vardiya')),
            ],
        ),
    ]
