# Generated by Django 5.2.7 on 2025-10-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_vardiya_durum_vardiyaiptalistegi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vardiyaiptalistegi',
            name='orijinal_vardiya_durumu',
            field=models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal_istegi', 'İptal İsteği'), ('iptal', 'İptal Edildi'), ('taslak', 'Taslak')], default='taslak', max_length=20),
        ),
    ]
