# Generated by Django 5.2.7 on 2025-10-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_vardiyaiptalistegi_orijinal_vardiya_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vardiya',
            name='gercek_baslangic_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç Zamanı'),
        ),
        migrations.AddField(
            model_name='vardiya',
            name='gercek_bitis_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Bitiş Zamanı'),
        ),
        migrations.AlterField(
            model_name='vardiya',
            name='baslangic_zamani',
            field=models.DateTimeField(verbose_name='Planlanan Başlangıç Zamanı'),
        ),
        migrations.AlterField(
            model_name='vardiya',
            name='bitis_zamani',
            field=models.DateTimeField(verbose_name='Planlanan Bitiş Zamanı'),
        ),
        migrations.AlterField(
            model_name='vardiya',
            name='durum',
            field=models.CharField(choices=[('planlandi', 'Planlandı'), ('baslatildi', 'Başlatıldı'), ('tamamlandi', 'Tamamlandı'), ('iptal_istegi', 'İptal İsteği'), ('iptal', 'İptal Edildi'), ('taslak', 'Taslak')], default='taslak', max_length=20),
        ),
        migrations.AlterField(
            model_name='vardiyaiptalistegi',
            name='orijinal_vardiya_durumu',
            field=models.CharField(choices=[('planlandi', 'Planlandı'), ('baslatildi', 'Başlatıldı'), ('tamamlandi', 'Tamamlandı'), ('iptal_istegi', 'İptal İsteği'), ('iptal', 'İptal Edildi'), ('taslak', 'Taslak')], default='taslak', max_length=20),
        ),
    ]
